regions = [
    "Kanto",
    "Johto",
    "Hoenn",
    "Sinnoh",
    "Unova",
    "Kalos",
    "Alola",
    "Galar",
    "Paldea",
]

dex_pokemon = [
    {
        "pokemon": "Bulbasaur",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Ivysaur",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Venusaur",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Charmander",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Charmeleon",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Charizard",
        "primary_type": "Fire",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Squirtle",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Wartortle",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Blastoise",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Caterpie",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Metapod",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Butterfree",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Weedle",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Kakuna",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Beedrill",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Pidgey",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Pidgeotto",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Pidgeot",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Rattata",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Raticate",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Spearow",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Fearow",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Ekans",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Arbok",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Pikachu",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Raichu",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Sandshrew",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Sandslash",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Nidoran♀",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Nidorina",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Nidoqueen",
        "primary_type": "Poison",
        "secondary_type": "Ground",
        "region": "Kanto",
    },
    {
        "pokemon": "Nidoran♂",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Nidorino",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Nidoking",
        "primary_type": "Poison",
        "secondary_type": "Ground",
        "region": "Kanto",
    },
    {
        "pokemon": "Clefairy",
        "primary_type": "Fairy",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Clefable",
        "primary_type": "Fairy",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Vulpix",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Ninetales",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Jigglypuff",
        "primary_type": "Normal",
        "secondary_type": "Fairy",
        "region": "Kanto",
    },
    {
        "pokemon": "Wigglytuff",
        "primary_type": "Normal",
        "secondary_type": "Fairy",
        "region": "Kanto",
    },
    {
        "pokemon": "Zubat",
        "primary_type": "Poison",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Golbat",
        "primary_type": "Poison",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Oddish",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Gloom",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Vileplume",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Paras",
        "primary_type": "Bug",
        "secondary_type": "Grass",
        "region": "Kanto",
    },
    {
        "pokemon": "Parasect",
        "primary_type": "Bug",
        "secondary_type": "Grass",
        "region": "Kanto",
    },
    {
        "pokemon": "Venonat",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Venomoth",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Diglett",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Dugtrio",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Meowth",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Persian",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Psyduck",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Golduck",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Mankey",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Primeape",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Growlithe",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Arcanine",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Poliwag",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Poliwhirl",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Poliwrath",
        "primary_type": "Water",
        "secondary_type": "Fighting",
        "region": "Kanto",
    },
    {
        "pokemon": "Abra",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Kadabra",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Alakazam",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Machop",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Machoke",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Machamp",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Bellsprout",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Weepinbell",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Victreebel",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Tentacool",
        "primary_type": "Water",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Tentacruel",
        "primary_type": "Water",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Geodude",
        "primary_type": "Rock",
        "secondary_type": "Ground",
        "region": "Kanto",
    },
    {
        "pokemon": "Graveler",
        "primary_type": "Rock",
        "secondary_type": "Ground",
        "region": "Kanto",
    },
    {
        "pokemon": "Golem",
        "primary_type": "Rock",
        "secondary_type": "Ground",
        "region": "Kanto",
    },
    {
        "pokemon": "Ponyta",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Rapidash",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Slowpoke",
        "primary_type": "Water",
        "secondary_type": "Psychic",
        "region": "Kanto",
    },
    {
        "pokemon": "Slowbro",
        "primary_type": "Water",
        "secondary_type": "Psychic",
        "region": "Kanto",
    },
    {
        "pokemon": "Magnemite",
        "primary_type": "Electric",
        "secondary_type": "Steel",
        "region": "Kanto",
    },
    {
        "pokemon": "Magneton",
        "primary_type": "Electric",
        "secondary_type": "Steel",
        "region": "Kanto",
    },
    {
        "pokemon": "Farfetch'd",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Doduo",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Dodrio",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Seel",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Dewgong",
        "primary_type": "Water",
        "secondary_type": "Ice",
        "region": "Kanto",
    },
    {
        "pokemon": "Grimer",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Muk",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Shellder",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Cloyster",
        "primary_type": "Water",
        "secondary_type": "Ice",
        "region": "Kanto",
    },
    {
        "pokemon": "Gastly",
        "primary_type": "Ghost",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Haunter",
        "primary_type": "Ghost",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Gengar",
        "primary_type": "Ghost",
        "secondary_type": "Poison",
        "region": "Kanto",
    },
    {
        "pokemon": "Onix",
        "primary_type": "Rock",
        "secondary_type": "Ground",
        "region": "Kanto",
    },
    {
        "pokemon": "Drowzee",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Hypno",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Krabby",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Kingler",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Voltorb",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Electrode",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Exeggcute",
        "primary_type": "Grass",
        "secondary_type": "Psychic",
        "region": "Kanto",
    },
    {
        "pokemon": "Exeggutor",
        "primary_type": "Grass",
        "secondary_type": "Psychic",
        "region": "Kanto",
    },
    {
        "pokemon": "Cubone",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Marowak",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Hitmonlee",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Hitmonchan",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Lickitung",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Koffing",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Weezing",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Rhyhorn",
        "primary_type": "Ground",
        "secondary_type": "Rock",
        "region": "Kanto",
    },
    {
        "pokemon": "Rhydon",
        "primary_type": "Ground",
        "secondary_type": "Rock",
        "region": "Kanto",
    },
    {
        "pokemon": "Chansey",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Tangela",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Kangaskhan",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Horsea",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Seadra",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Goldeen",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Seaking",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Staryu",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Starmie",
        "primary_type": "Water",
        "secondary_type": "Psychic",
        "region": "Kanto",
    },
    {
        "pokemon": "Mr. Mime",
        "primary_type": "Psychic",
        "secondary_type": "Fairy",
        "region": "Kanto",
    },
    {
        "pokemon": "Scyther",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Jynx",
        "primary_type": "Ice",
        "secondary_type": "Psychic",
        "region": "Kanto",
    },
    {
        "pokemon": "Electabuzz",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Magmar",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Pinsir",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Tauros",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Magikarp",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Gyarados",
        "primary_type": "Water",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Lapras",
        "primary_type": "Water",
        "secondary_type": "Ice",
        "region": "Kanto",
    },
    {
        "pokemon": "Ditto",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Eevee",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Vaporeon",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Jolteon",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Flareon",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Porygon",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Omanyte",
        "primary_type": "Rock",
        "secondary_type": "Water",
        "region": "Kanto",
    },
    {
        "pokemon": "Omastar",
        "primary_type": "Rock",
        "secondary_type": "Water",
        "region": "Kanto",
    },
    {
        "pokemon": "Kabuto",
        "primary_type": "Rock",
        "secondary_type": "Water",
        "region": "Kanto",
    },
    {
        "pokemon": "Kabutops",
        "primary_type": "Rock",
        "secondary_type": "Water",
        "region": "Kanto",
    },
    {
        "pokemon": "Aerodactyl",
        "primary_type": "Rock",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Snorlax",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Articuno",
        "primary_type": "Ice",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Zapdos",
        "primary_type": "Electric",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Moltres",
        "primary_type": "Fire",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Dratini",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Dragonair",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Dragonite",
        "primary_type": "Dragon",
        "secondary_type": "Flying",
        "region": "Kanto",
    },
    {
        "pokemon": "Mewtwo",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Mew",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Kanto",
    },
    {
        "pokemon": "Chikorita",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Bayleef",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Meganium",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Cyndaquil",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Quilava",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Typhlosion",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Totodile",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Croconaw",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Feraligatr",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Sentret",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Furret",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Hoothoot",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Noctowl",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Ledyba",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Ledian",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Spinarak",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Johto",
    },
    {
        "pokemon": "Ariados",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Johto",
    },
    {
        "pokemon": "Crobat",
        "primary_type": "Poison",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Chinchou",
        "primary_type": "Water",
        "secondary_type": "Electric",
        "region": "Johto",
    },
    {
        "pokemon": "Lanturn",
        "primary_type": "Water",
        "secondary_type": "Electric",
        "region": "Johto",
    },
    {
        "pokemon": "Pichu",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Cleffa",
        "primary_type": "Fairy",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Igglybuff",
        "primary_type": "Normal",
        "secondary_type": "Fairy",
        "region": "Johto",
    },
    {
        "pokemon": "Togepi",
        "primary_type": "Fairy",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Togetic",
        "primary_type": "Fairy",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Natu",
        "primary_type": "Psychic",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Xatu",
        "primary_type": "Psychic",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Mareep",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Flaaffy",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Ampharos",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Bellossom",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Marill",
        "primary_type": "Water",
        "secondary_type": "Fairy",
        "region": "Johto",
    },
    {
        "pokemon": "Azumarill",
        "primary_type": "Water",
        "secondary_type": "Fairy",
        "region": "Johto",
    },
    {
        "pokemon": "Sudowoodo",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Politoed",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Hoppip",
        "primary_type": "Grass",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Skiploom",
        "primary_type": "Grass",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Jumpluff",
        "primary_type": "Grass",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Aipom",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Sunkern",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Sunflora",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Yanma",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Wooper",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Johto",
    },
    {
        "pokemon": "Quagsire",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Johto",
    },
    {
        "pokemon": "Espeon",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Umbreon",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Murkrow",
        "primary_type": "Dark",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Slowking",
        "primary_type": "Water",
        "secondary_type": "Psychic",
        "region": "Johto",
    },
    {
        "pokemon": "Misdreavous",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Unown",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Wobbuffet",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Girafarig",
        "primary_type": "Normal",
        "secondary_type": "Psychic",
        "region": "Johto",
    },
    {
        "pokemon": "Pineco",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Forretress",
        "primary_type": "Bug",
        "secondary_type": "Steel",
        "region": "Johto",
    },
    {
        "pokemon": "Dunsparce",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Gligar",
        "primary_type": "Ground",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Steelix",
        "primary_type": "Steel",
        "secondary_type": "Ground",
        "region": "Johto",
    },
    {
        "pokemon": "Snubbull",
        "primary_type": "Fairy",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Granbull",
        "primary_type": "Fairy",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Qwilfish",
        "primary_type": "Water",
        "secondary_type": "Poison",
        "region": "Johto",
    },
    {
        "pokemon": "Scizor",
        "primary_type": "Bug",
        "secondary_type": "Steel",
        "region": "Johto",
    },
    {
        "pokemon": "Shuckle",
        "primary_type": "Bug",
        "secondary_type": "Rock",
        "region": "Johto",
    },
    {
        "pokemon": "Heracross",
        "primary_type": "Bug",
        "secondary_type": "Fighting",
        "region": "Johto",
    },
    {
        "pokemon": "Sneasel",
        "primary_type": "Dark",
        "secondary_type": "Ice",
        "region": "Johto",
    },
    {
        "pokemon": "Teddiursa",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Ursaring",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Slugma",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Magcargo",
        "primary_type": "Fire",
        "secondary_type": "Rock",
        "region": "Johto",
    },
    {
        "pokemon": "Swinub",
        "primary_type": "Ice",
        "secondary_type": "Ground",
        "region": "Johto",
    },
    {
        "pokemon": "Piloswine",
        "primary_type": "Ice",
        "secondary_type": "Ground",
        "region": "Johto",
    },
    {
        "pokemon": "Corsola",
        "primary_type": "Water",
        "secondary_type": "Rock",
        "region": "Johto",
    },
    {
        "pokemon": "Remoraid",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Octillery",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Delibird",
        "primary_type": "Ice",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Mantine",
        "primary_type": "Water",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Skarmory",
        "primary_type": "Steel",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Houndour",
        "primary_type": "Dark",
        "secondary_type": "Fire",
        "region": "Johto",
    },
    {
        "pokemon": "Houndoom",
        "primary_type": "Dark",
        "secondary_type": "Fire",
        "region": "Johto",
    },
    {
        "pokemon": "Kingdra",
        "primary_type": "Water",
        "secondary_type": "Dragon",
        "region": "Johto",
    },
    {
        "pokemon": "Phanpy",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Donphan",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Porygon2",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Stantler",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Smeargle",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Tyrogue",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Hitmontop",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Smoochum",
        "primary_type": "Ice",
        "secondary_type": "Psychic",
        "region": "Johto",
    },
    {
        "pokemon": "Elekid",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Magby",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Miltank",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Blissey",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Raikou",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Entei",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Suicune",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Johto",
    },
    {
        "pokemon": "Larvitar",
        "primary_type": "Rock",
        "secondary_type": "Ground",
        "region": "Johto",
    },
    {
        "pokemon": "Pupitar",
        "primary_type": "Rock",
        "secondary_type": "Ground",
        "region": "Johto",
    },
    {
        "pokemon": "Tyranitar",
        "primary_type": "Rock",
        "secondary_type": "Dark",
        "region": "Johto",
    },
    {
        "pokemon": "Lugia",
        "primary_type": "Psychic",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Ho-Oh",
        "primary_type": "Fire",
        "secondary_type": "Flying",
        "region": "Johto",
    },
    {
        "pokemon": "Celebi",
        "primary_type": "Psychic",
        "secondary_type": "Grass",
        "region": "Johto",
    },
    {
        "pokemon": "Treecko",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Grovyle",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Sceptile",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Torchic",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Combusken",
        "primary_type": "Fire",
        "secondary_type": "Fighting",
        "region": "Hoenn",
    },
    {
        "pokemon": "Blaziken",
        "primary_type": "Fire",
        "secondary_type": "Fighting",
        "region": "Hoenn",
    },
    {
        "pokemon": "Mudkip",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Marshtomp",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Hoenn",
    },
    {
        "pokemon": "Swampert",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Hoenn",
    },
    {
        "pokemon": "Poochyena",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Mightyena",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Zigzagoon",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Linoone",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Wurmple",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Silcoon",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Beautifly",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Cascoon",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Dustox",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Hoenn",
    },
    {
        "pokemon": "Lotad",
        "primary_type": "Water",
        "secondary_type": "Grass",
        "region": "Hoenn",
    },
    {
        "pokemon": "Lombre",
        "primary_type": "Water",
        "secondary_type": "Grass",
        "region": "Hoenn",
    },
    {
        "pokemon": "Ludicolo",
        "primary_type": "Water",
        "secondary_type": "Grass",
        "region": "Hoenn",
    },
    {
        "pokemon": "Seedot",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Nuzleaf",
        "primary_type": "Grass",
        "secondary_type": "Dark",
        "region": "Hoenn",
    },
    {
        "pokemon": "Shiftry",
        "primary_type": "Grass",
        "secondary_type": "Dark",
        "region": "Hoenn",
    },
    {
        "pokemon": "Taillow",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Swellow",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Wingull",
        "primary_type": "Water",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Pelipper",
        "primary_type": "Water",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Ralts",
        "primary_type": "Psychic",
        "secondary_type": "Fairy",
        "region": "Hoenn",
    },
    {
        "pokemon": "Kirlia",
        "primary_type": "Psychic",
        "secondary_type": "Fairy",
        "region": "Hoenn",
    },
    {
        "pokemon": "Gardevoir",
        "primary_type": "Psychic",
        "secondary_type": "Fairy",
        "region": "Hoenn",
    },
    {
        "pokemon": "Surskit",
        "primary_type": "Bug",
        "secondary_type": "Water",
        "region": "Hoenn",
    },
    {
        "pokemon": "Masquerain",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Shroomish",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Breloom",
        "primary_type": "Grass",
        "secondary_type": "Fighting",
        "region": "Hoenn",
    },
    {
        "pokemon": "Slakoth",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Vigoroth",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Slaking",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Nincada",
        "primary_type": "Bug",
        "secondary_type": "Ground",
        "region": "Hoenn",
    },
    {
        "pokemon": "Ninjask",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Shedinja",
        "primary_type": "Bug",
        "secondary_type": "Ghost",
        "region": "Hoenn",
    },
    {
        "pokemon": "Whismur",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Loudred",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Exploud",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Makuhita",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Hariyama",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Azurill",
        "primary_type": "Normal",
        "secondary_type": "Fairy",
        "region": "Hoenn",
    },
    {
        "pokemon": "Nosepass",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Skitty",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Delcatty",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Sableye",
        "primary_type": "Dark",
        "secondary_type": "Ghost",
        "region": "Hoenn",
    },
    {
        "pokemon": "Mawile",
        "primary_type": "Steel",
        "secondary_type": "Fairy",
        "region": "Hoenn",
    },
    {
        "pokemon": "Aron",
        "primary_type": "Steel",
        "secondary_type": "Rock",
        "region": "Hoenn",
    },
    {
        "pokemon": "Lairon",
        "primary_type": "Steel",
        "secondary_type": "Rock",
        "region": "Hoenn",
    },
    {
        "pokemon": "Aggron",
        "primary_type": "Steel",
        "secondary_type": "Rock",
        "region": "Hoenn",
    },
    {
        "pokemon": "Meditite",
        "primary_type": "Fighting",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Medicham",
        "primary_type": "Fighting",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Electrike",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Manectric",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Plusle",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Minun",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Volbeat",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Illumise",
        "primary_type": "Bug",
        "secondary_type": "Electric",
        "region": "Hoenn",
    },
    {
        "pokemon": "Roselia",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Hoenn",
    },
    {
        "pokemon": "Gulpin",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Swalot",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Carvanha",
        "primary_type": "Water",
        "secondary_type": "Dark",
        "region": "Hoenn",
    },
    {
        "pokemon": "Sharpedo",
        "primary_type": "Water",
        "secondary_type": "Dark",
        "region": "Hoenn",
    },
    {
        "pokemon": "Wailmer",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Wailord",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Numel",
        "primary_type": "Fire",
        "secondary_type": "Ground",
        "region": "Hoenn",
    },
    {
        "pokemon": "Camerupt",
        "primary_type": "Fire",
        "secondary_type": "Ground",
        "region": "Hoenn",
    },
    {
        "pokemon": "Torkoal",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Spoink",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Grumpig",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Spinda",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Trapinch",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Vibrava",
        "primary_type": "Ground",
        "secondary_type": "Dragon",
        "region": "Hoenn",
    },
    {
        "pokemon": "Flygon",
        "primary_type": "Ground",
        "secondary_type": "Dragon",
        "region": "Hoenn",
    },
    {
        "pokemon": "Cacnea",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Cacturne",
        "primary_type": "Grass",
        "secondary_type": "Dark",
        "region": "Hoenn",
    },
    {
        "pokemon": "Swablu",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Altaria",
        "primary_type": "Dragon",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Zangoose",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Seviper",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Lunatone",
        "primary_type": "Rock",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Solrock",
        "primary_type": "Rock",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Barboach",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Hoenn",
    },
    {
        "pokemon": "Whiscash",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Hoenn",
    },
    {
        "pokemon": "Corphish",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Crawdaunt",
        "primary_type": "Water",
        "secondary_type": "Dark",
        "region": "Hoenn",
    },
    {
        "pokemon": "Baltoy",
        "primary_type": "Ground",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Claydol",
        "primary_type": "Ground",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Lileep",
        "primary_type": "Rock",
        "secondary_type": "Grass",
        "region": "Hoenn",
    },
    {
        "pokemon": "Cradily",
        "primary_type": "Rock",
        "secondary_type": "Grass",
        "region": "Hoenn",
    },
    {
        "pokemon": "Anorith",
        "primary_type": "Rock",
        "secondary_type": "Bug",
        "region": "Hoenn",
    },
    {
        "pokemon": "Armaldo",
        "primary_type": "Rock",
        "secondary_type": "Bug",
        "region": "Hoenn",
    },
    {
        "pokemon": "Feebas",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Milotic",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Castform",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Kecleon",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Shuppet",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Banette",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Duskull",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Dusclops",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Tropius",
        "primary_type": "Grass",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Chimecho",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Absol",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Wynaut",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Snorunt",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Glalie",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Spheal",
        "primary_type": "Ice",
        "secondary_type": "Water",
        "region": "Hoenn",
    },
    {
        "pokemon": "Sealeo",
        "primary_type": "Ice",
        "secondary_type": "Water",
        "region": "Hoenn",
    },
    {
        "pokemon": "Walrein",
        "primary_type": "Ice",
        "secondary_type": "Water",
        "region": "Hoenn",
    },
    {
        "pokemon": "Clamperl",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Huntail",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Gorebyss",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Relicanth",
        "primary_type": "Water",
        "secondary_type": "Rock",
        "region": "Hoenn",
    },
    {
        "pokemon": "Luvdisc",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Bagon",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Shelgon",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Salamence",
        "primary_type": "Dragon",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Beldum",
        "primary_type": "Steel",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Metang",
        "primary_type": "Steel",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Metagross",
        "primary_type": "Steel",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Regirock",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Regice",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Registeel",
        "primary_type": "Steel",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Latias",
        "primary_type": "Dragon",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Latios",
        "primary_type": "Dragon",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Kyogre",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Groudon",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Rayquaza",
        "primary_type": "Dragon",
        "secondary_type": "Flying",
        "region": "Hoenn",
    },
    {
        "pokemon": "Jirachi",
        "primary_type": "Steel",
        "secondary_type": "Psychic",
        "region": "Hoenn",
    },
    {
        "pokemon": "Deoxys",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Hoenn",
    },
    {
        "pokemon": "Turtwig",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Grotle",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Torterra",
        "primary_type": "Grass",
        "secondary_type": "Ground",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Chimchar",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Monferno",
        "primary_type": "Fire",
        "secondary_type": "Fighting",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Infernape",
        "primary_type": "Fire",
        "secondary_type": "Fighting",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Piplup",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Prinplup",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Empoleon",
        "primary_type": "Water",
        "secondary_type": "Steel",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Starly",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Staravia",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Staraptor",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Bidoof",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Bibarel",
        "primary_type": "Normal",
        "secondary_type": "Water",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Kricketot",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Kricketune",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Shinx",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Luxio",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Luxray",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Budew",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Roserade",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Cranidos",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Rampardos",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Shieldon",
        "primary_type": "Rock",
        "secondary_type": "Steel",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Bastiodon",
        "primary_type": "Rock",
        "secondary_type": "Steel",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Burmy",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Wormadam",
        "primary_type": "Bug",
        "secondary_type": "Grass",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Mothim",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Combee",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Vespiquen",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Pachirisu",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Buizel",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Floatzel",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Cherubi",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Cherrim",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Shellos",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Gastrodon",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Ambipom",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Drifloon",
        "primary_type": "Ghost",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Drifblim",
        "primary_type": "Psychic",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Buneary",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Lopunny",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Mismagius",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Honchkrow",
        "primary_type": "Dark",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Glameow",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Purugly",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Chingling",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Stunky",
        "primary_type": "Poison",
        "secondary_type": "Dark",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Skuntank",
        "primary_type": "Poison",
        "secondary_type": "Dark",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Bronzor",
        "primary_type": "Steel",
        "secondary_type": "Psychic",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Bronzong",
        "primary_type": "Steel",
        "secondary_type": "Psychic",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Bonsly",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Mime Jr.",
        "primary_type": "Psychic",
        "secondary_type": "Fairy",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Happiny",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Chatot",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Spiritomb",
        "primary_type": "Ghost",
        "secondary_type": "Dark",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Gible",
        "primary_type": "Dragon",
        "secondary_type": "Ground",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Gabite",
        "primary_type": "Dragon",
        "secondary_type": "Ground",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Garchomp",
        "primary_type": "Dragon",
        "secondary_type": "Ground",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Munchlax",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Riolu",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Lucario",
        "primary_type": "Fighting",
        "secondary_type": "Steel",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Hippopotas",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Hippowdon",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Skorupi",
        "primary_type": "Poison",
        "secondary_type": "Bug",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Drapion",
        "primary_type": "Poison",
        "secondary_type": "Dark",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Croagunk",
        "primary_type": "Poison",
        "secondary_type": "Fighting",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Toxicroak",
        "primary_type": "Poison",
        "secondary_type": "Fighting",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Carnivine",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Finneon",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Lumineon",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Mantyke",
        "primary_type": "Water",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Snover",
        "primary_type": "Grass",
        "secondary_type": "Ice",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Abomasnow",
        "primary_type": "Grass",
        "secondary_type": "Ice",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Weavile",
        "primary_type": "Dark",
        "secondary_type": "Ice",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Magnezone",
        "primary_type": "Electric",
        "secondary_type": "Steel",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Lickilicky",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Rhyperior",
        "primary_type": "Ground",
        "secondary_type": "Rock",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Tangrowth",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Electivire",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Magmortar",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Togekiss",
        "primary_type": "Fairy",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Yanmega",
        "primary_type": "Bug",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Leafeon",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Glaceon",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Gliscor",
        "primary_type": "Ground",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Mamoswine",
        "primary_type": "Ice",
        "secondary_type": "Ground",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Porygon-Z",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Gallade",
        "primary_type": "Psychic",
        "secondary_type": "Fighting",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Probopass",
        "primary_type": "Rock",
        "secondary_type": "Steel",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Dusknoir",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Froslass",
        "primary_type": "Ice",
        "secondary_type": "Ghost",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Rotom",
        "primary_type": "Electric",
        "secondary_type": "Ghost",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Uxie",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Mesprit",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Azelf",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Dialga",
        "primary_type": "Steel",
        "secondary_type": "Dragon",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Palkia",
        "primary_type": "Water",
        "secondary_type": "Dragon",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Heatran",
        "primary_type": "Fire",
        "secondary_type": "Steel",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Regigigas",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Giratina",
        "primary_type": "Ghost",
        "secondary_type": "Dragon",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Cresselia",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Phione",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Manaphy",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Darkrai",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Shaymin",
        "primary_type": "Grass",
        "secondary_type": "Flying",
        "region": "Sinnoh",
    },
    {
        "pokemon": "Arceus",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Sinnoh",
    },
    {
        "pokemon": "Victini",
        "primary_type": "Psychic",
        "secondary_type": "Fire",
        "region": "Unova",
    },
    {
        "pokemon": "Snivy",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Servine",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Serperior",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Tepig",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Pignite",
        "primary_type": "Fire",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Emboar",
        "primary_type": "Fire",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Oshawott",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Dewott",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Samurott",
        "primary_type": "Water",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Patrat",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Watchog",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Lillipup",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Herdier",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Stoutland",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Purrloin",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Liepard",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Pansage",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Simisage",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Pansear",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Simisear",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Panpour",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Simipour",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Munna",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Musharna",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Pidove",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Tranquill",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Unfezant",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Blitzle",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Zebstrika",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Roggenrola",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Boldore",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Gigalith",
        "primary_type": "Rock",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Woobat",
        "primary_type": "Psychic",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Swoobat",
        "primary_type": "Psychic",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Drilbur",
        "primary_type": "Ground",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Excadrill",
        "primary_type": "Ground",
        "secondary_type": "Steel",
        "region": "Unova",
    },
    {
        "pokemon": "Audino",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Timburr",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Gurdurr",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Conkeldurr",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Tympole",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Palpitoad",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Unova",
    },
    {
        "pokemon": "Seismitoad",
        "primary_type": "Water",
        "secondary_type": "Ground",
        "region": "Unova",
    },
    {
        "pokemon": "Throh",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Sawk",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Sewaddle",
        "primary_type": "Bug",
        "secondary_type": "Grass",
        "region": "Unova",
    },
    {
        "pokemon": "Swadloon",
        "primary_type": "Bug",
        "secondary_type": "Grass",
        "region": "Unova",
    },
    {
        "pokemon": "Leavanny",
        "primary_type": "Bug",
        "secondary_type": "Grass",
        "region": "Unova",
    },
    {
        "pokemon": "Venipede",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Unova",
    },
    {
        "pokemon": "Whirlipede",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Unova",
    },
    {
        "pokemon": "Scolipede",
        "primary_type": "Bug",
        "secondary_type": "Poison",
        "region": "Unova",
    },
    {
        "pokemon": "Cottonee",
        "primary_type": "Grass",
        "secondary_type": "Fairy",
        "region": "Unova",
    },
    {
        "pokemon": "Whimsicott",
        "primary_type": "Grass",
        "secondary_type": "Fairy",
        "region": "Unova",
    },
    {
        "pokemon": "Petilil",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Lilligant",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Basculin",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Sandile",
        "primary_type": "Ground",
        "secondary_type": "Dark",
        "region": "Unova",
    },
    {
        "pokemon": "Krokorok",
        "primary_type": "Ground",
        "secondary_type": "Dark",
        "region": "Unova",
    },
    {
        "pokemon": "Krookodile",
        "primary_type": "Ground",
        "secondary_type": "Dark",
        "region": "Unova",
    },
    {
        "pokemon": "Darumaka",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Darmanitan",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Maractus",
        "primary_type": "Grass",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Dwebble",
        "primary_type": "Bug",
        "secondary_type": "Rock",
        "region": "Unova",
    },
    {
        "pokemon": "Crustle",
        "primary_type": "Bug",
        "secondary_type": "Rock",
        "region": "Unova",
    },
    {
        "pokemon": "Scraggy",
        "primary_type": "Dark",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Scrafty",
        "primary_type": "Dark",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Sigilyph",
        "primary_type": "Psychic",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Yamask",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Cofagrigus",
        "primary_type": "Ghost",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Tirtouga",
        "primary_type": "Water",
        "secondary_type": "Rock",
        "region": "Unova",
    },
    {
        "pokemon": "Carracosta",
        "primary_type": "Water",
        "secondary_type": "Rock",
        "region": "Unova",
    },
    {
        "pokemon": "Archen",
        "primary_type": "Rock",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Archeops",
        "primary_type": "Rock",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Trubbish",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Garbodor",
        "primary_type": "Poison",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Zorua",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Zoroark",
        "primary_type": "Dark",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Minccino",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Cinccino",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Gothita",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Gothorita",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Gothitelle",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Solosis",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Duosion",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Reuniclus",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Ducklett",
        "primary_type": "Water",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Swanna",
        "primary_type": "Water",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Vanillite",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Vanillish",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Vanilluxe",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Deerling",
        "primary_type": "Normal",
        "secondary_type": "Grass",
        "region": "Unova",
    },
    {
        "pokemon": "Sawsbuck",
        "primary_type": "Normal",
        "secondary_type": "Grass",
        "region": "Unova",
    },
    {
        "pokemon": "Emolga",
        "primary_type": "Electric",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Karrablast",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Escavalier",
        "primary_type": "Bug",
        "secondary_type": "Steel",
        "region": "Unova",
    },
    {
        "pokemon": "Foongus",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Unova",
    },
    {
        "pokemon": "Amoonguss",
        "primary_type": "Grass",
        "secondary_type": "Poison",
        "region": "Unova",
    },
    {
        "pokemon": "Frillish",
        "primary_type": "Water",
        "secondary_type": "Ghost",
        "region": "Unova",
    },
    {
        "pokemon": "Jellicent",
        "primary_type": "Water",
        "secondary_type": "Ghost",
        "region": "Unova",
    },
    {
        "pokemon": "Alomomola",
        "primary_type": "Water",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Joltik",
        "primary_type": "Bug",
        "secondary_type": "Electric",
        "region": "Unova",
    },
    {
        "pokemon": "Galvantula",
        "primary_type": "Bug",
        "secondary_type": "Electric",
        "region": "Unova",
    },
    {
        "pokemon": "Ferroseed",
        "primary_type": "Grass",
        "secondary_type": "Steel",
        "region": "Unova",
    },
    {
        "pokemon": "Ferrothorn",
        "primary_type": "Grass",
        "secondary_type": "Steel",
        "region": "Unova",
    },
    {
        "pokemon": "Klink",
        "primary_type": "Steel",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Klang",
        "primary_type": "Steel",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Klinklang",
        "primary_type": "Steel",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Tynamo",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Eelektrik",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Eelektross",
        "primary_type": "Electric",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Elgyem",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Beheeyem",
        "primary_type": "Psychic",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Litwick",
        "primary_type": "Ghost",
        "secondary_type": "Fire",
        "region": "Unova",
    },
    {
        "pokemon": "Lampent",
        "primary_type": "Ghost",
        "secondary_type": "Fire",
        "region": "Unova",
    },
    {
        "pokemon": "Chandelure",
        "primary_type": "Ghost",
        "secondary_type": "Fire",
        "region": "Unova",
    },
    {
        "pokemon": "Axew",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Fraxure",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Haxorus",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Cubchoo",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Beartic",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Cryogonal",
        "primary_type": "Ice",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Shelmet",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Accelgor",
        "primary_type": "Bug",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Stunfisk",
        "primary_type": "Ground",
        "secondary_type": "Electric",
        "region": "Unova",
    },
    {
        "pokemon": "Mienfoo",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Mienshao",
        "primary_type": "Fighting",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Druddigon",
        "primary_type": "Dragon",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Golett",
        "primary_type": "Ground",
        "secondary_type": "Ghost",
        "region": "Unova",
    },
    {
        "pokemon": "Golurk",
        "primary_type": "Ground",
        "secondary_type": "Ghost",
        "region": "Unova",
    },
    {
        "pokemon": "Pawniard",
        "primary_type": "Dark",
        "secondary_type": "Steel",
        "region": "Unova",
    },
    {
        "pokemon": "Bisharp",
        "primary_type": "Dark",
        "secondary_type": "Steel",
        "region": "Unova",
    },
    {
        "pokemon": "Bouffalant",
        "primary_type": "Normal",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Rufflet",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Braviary",
        "primary_type": "Normal",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Vullaby",
        "primary_type": "Dark",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Mandibuzz",
        "primary_type": "Dark",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Heatmor",
        "primary_type": "Fire",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Durant",
        "primary_type": "Bug",
        "secondary_type": "Steel",
        "region": "Unova",
    },
    {
        "pokemon": "Deino",
        "primary_type": "Dark",
        "secondary_type": "Dragon",
        "region": "Unova",
    },
    {
        "pokemon": "Zweilous",
        "primary_type": "Dark",
        "secondary_type": "Dragon",
        "region": "Unova",
    },
    {
        "pokemon": "Hydreigon",
        "primary_type": "Dark",
        "secondary_type": "Dragon",
        "region": "Unova",
    },
    {
        "pokemon": "Larvesta",
        "primary_type": "Bug",
        "secondary_type": "Fire",
        "region": "Unova",
    },
    {
        "pokemon": "Volcarona",
        "primary_type": "Bug",
        "secondary_type": "Fire",
        "region": "Unova",
    },
    {
        "pokemon": "Cobalion",
        "primary_type": "Steel",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Terrakion",
        "primary_type": "Rock",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Virizion",
        "primary_type": "Grass",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Tornadus",
        "primary_type": "Flying",
        "secondary_type": None,
        "region": "Unova",
    },
    {
        "pokemon": "Thundurus",
        "primary_type": "Electric",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Reshiram",
        "primary_type": "Dragon",
        "secondary_type": "Fire",
        "region": "Unova",
    },
    {
        "pokemon": "Zekrom",
        "primary_type": "Dragon",
        "secondary_type": "Electric",
        "region": "Unova",
    },
    {
        "pokemon": "Landorus",
        "primary_type": "Ground",
        "secondary_type": "Flying",
        "region": "Unova",
    },
    {
        "pokemon": "Kyurem",
        "primary_type": "Dragon",
        "secondary_type": "Ice",
        "region": "Unova",
    },
    {
        "pokemon": "Keldeo",
        "primary_type": "Water",
        "secondary_type": "Fighting",
        "region": "Unova",
    },
    {
        "pokemon": "Meloetta",
        "primary_type": "Normal",
        "secondary_type": "Psychic",
        "region": "Unova",
    },
    {
        "pokemon": "Genesect",
        "primary_type": "Bug",
        "secondary_type": "Steel",
        "region": "Unova",
    },
]
